"""settings pricing flags commission plans provider credentials

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-09 21:55:47.189394
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # country_code وvehicle_category أنشأتهما 0002؛ `create_type=False` يمنع
    # alembic من إعادة CREATE TYPE لهما مع كل جدول جديد يستعملهما.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_settings',
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('commission_enabled', sa.Boolean(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('applies_to', sa.Enum('all_rides', 'cashless_rides', name='commission_applies_to'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commission_percent >= 0 AND commission_percent <= 100', name=op.f('ck_commission_settings_commission_percent_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commission_settings'))
    )
    op.create_index(op.f('ix_commission_settings_country_code'), 'commission_settings', ['country_code'], unique=True)
    op.create_table('feature_flags',
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_flags')),
    sa.UniqueConstraint('country_code', 'feature_key', name=op.f('uq_feature_flags_country_code_feature_key'))
    )
    op.create_index(op.f('ix_feature_flags_country_code'), 'feature_flags', ['country_code'], unique=False)
    op.create_table('pricing_rules',
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('vehicle_category', postgresql.ENUM('economy', 'comfort', name='vehicle_category', create_type=False), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price_per_km', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price_per_min', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('minimum_fare', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('cancellation_fee', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_fare >= 0 AND price_per_km >= 0 AND price_per_min >= 0 AND minimum_fare >= 0 AND cancellation_fee >= 0', name=op.f('ck_pricing_rules_pricing_amounts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pricing_rules')),
    sa.UniqueConstraint('country_code', 'vehicle_category', name=op.f('uq_pricing_rules_country_code_vehicle_category'))
    )
    op.create_index(op.f('ix_pricing_rules_country_code'), 'pricing_rules', ['country_code'], unique=False)
    op.create_table('provider_credentials',
    sa.Column('provider_key', sa.Enum('mapbox', 'telr', 'sms', 'cliq_acquirer', 'fcm', 'payout', name='provider_key'), nullable=False),
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=True),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credentials'))
    )
    op.create_index('uq_provider_credentials_provider_key_country_code', 'provider_credentials', ['provider_key', 'country_code'], unique=True, postgresql_where=sa.text('country_code IS NOT NULL'))
    op.create_index('uq_provider_credentials_provider_key_global', 'provider_credentials', ['provider_key'], unique=True, postgresql_where=sa.text('country_code IS NULL'))
    op.create_table('subscription_plans',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration_type', sa.Enum('daily', 'weekly', 'monthly', name='subscription_duration_type'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', sa.Enum('LYD', 'JOD', name='currency'), nullable=False),
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price >= 0', name=op.f('ck_subscription_plans_subscription_price_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('country_code', 'name', name=op.f('uq_subscription_plans_country_code_name'))
    )
    op.create_index(op.f('ix_subscription_plans_country_code'), 'subscription_plans', ['country_code'], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'activate', 'deactivate', name='audit_action'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_admin_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_logs'))
    )
    op.create_index(op.f('ix_admin_audit_logs_entity_type'), 'admin_audit_logs', ['entity_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_audit_logs_entity_type'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_subscription_plans_country_code'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('uq_provider_credentials_provider_key_global', table_name='provider_credentials', postgresql_where=sa.text('country_code IS NULL'))
    op.drop_index('uq_provider_credentials_provider_key_country_code', table_name='provider_credentials', postgresql_where=sa.text('country_code IS NOT NULL'))
    op.drop_table('provider_credentials')
    op.drop_index(op.f('ix_pricing_rules_country_code'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index(op.f('ix_feature_flags_country_code'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_commission_settings_country_code'), table_name='commission_settings')
    op.drop_table('commission_settings')
    # ### end Alembic commands ###

    # أنواع ENUM لا تُسقط تلقائياً مع الجداول — بدون هذا يفشل upgrade بعد downgrade.
    # country_code وvehicle_category ليسا هنا: تنشئهما 0002 ولا تزال جداولها تستخدمهما.
    for enum_name in (
        'audit_action',
        'currency',
        'subscription_duration_type',
        'provider_key',
        'commission_applies_to',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
