"""rides table and pricing

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-09 22:29:07.469932
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # country_code وvehicle_category وcurrency أنشأتها ترحيلات سابقة؛
    # `create_type=False` يمنع إعادة CREATE TYPE لها. ride_status جديد هنا.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rides',
    sa.Column('rider_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('vehicle_category', postgresql.ENUM('economy', 'comfort', name='vehicle_category', create_type=False), nullable=False),
    sa.Column('pickup_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('pickup_address', sa.String(length=255), nullable=True),
    sa.Column('dropoff_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('dropoff_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('requested', 'searching', 'accepted', 'arrived', 'in_progress', 'completed', 'cancelled_by_rider', 'cancelled_by_driver', 'no_driver_found', name='ride_status'), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('duration_min', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('estimated_fare', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('final_fare', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cancellation_fee', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('currency', postgresql.ENUM('LYD', 'JOD', name='currency', create_type=False), nullable=False),
    sa.Column('commission_percent_at_ride', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cancelled_reason', sa.String(length=255), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('commission_percent_at_ride >= 0 AND commission_percent_at_ride <= 100', name=op.f('ck_rides_ride_commission_percent_range')),
    sa.CheckConstraint('distance_km >= 0 AND duration_min >= 0 AND estimated_fare >= 0 AND (final_fare IS NULL OR final_fare >= 0) AND (cancellation_fee IS NULL OR cancellation_fee >= 0)', name=op.f('ck_rides_ride_amounts_non_negative')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_rides_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], name=op.f('fk_rides_rider_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rides'))
    )
    op.create_index(op.f('ix_rides_country_code'), 'rides', ['country_code'], unique=False)
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_rider_id'), 'rides', ['rider_id'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_index('uq_rides_active_driver', 'rides', ['driver_id'], unique=True, postgresql_where=sa.text("status IN ('accepted', 'arrived', 'in_progress')"))
    op.create_index('uq_rides_active_rider', 'rides', ['rider_id'], unique=True, postgresql_where=sa.text("status IN ('requested', 'searching', 'accepted', 'arrived', 'in_progress')"))
    op.create_foreign_key(op.f('fk_drivers_current_ride_id_rides'), 'drivers', 'rides', ['current_ride_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_drivers_current_ride_id_rides'), 'drivers', type_='foreignkey')
    op.drop_index('uq_rides_active_rider', table_name='rides', postgresql_where=sa.text("status IN ('requested', 'searching', 'accepted', 'arrived', 'in_progress')"))
    op.drop_index('uq_rides_active_driver', table_name='rides', postgresql_where=sa.text("status IN ('accepted', 'arrived', 'in_progress')"))
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_rider_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_country_code'), table_name='rides')
    op.drop_table('rides')
    # ### end Alembic commands ###

    # postgres لا يُسقط ENUM مع جدوله — بدون هذا يفشل upgrade بعد downgrade
    op.execute('DROP TYPE IF EXISTS ride_status')
