"""wallet ledger topups withdrawals

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-10 00:45:27.349894
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # country_code أنشأته ترحيلة 0003؛ `create_type=False` يمنع إعادة
    # CREATE TYPE له. بقية الأنواع هنا جديدة فتُنشأ مع أعمدتها.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_settings',
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('transfer_daily_limit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('transfer_monthly_limit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_withdrawal_amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('transfer_daily_limit >= 0 AND transfer_monthly_limit >= 0 AND min_withdrawal_amount >= 0', name=op.f('ck_wallet_settings_wallet_limits_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_settings'))
    )
    op.create_index(op.f('ix_wallet_settings_country_code'), 'wallet_settings', ['country_code'], unique=True)
    op.create_table('wallet_transactions',
    sa.Column('owner_type', sa.Enum('rider', 'driver', name='wallet_owner_type'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('topup', 'ride_payment', 'ride_earning', 'commission', 'transfer_in', 'transfer_out', 'withdrawal', 'refund', 'subscription_payment', 'adjustment', name='wallet_transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type IN ('topup', 'ride_earning', 'transfer_in', 'refund') AND amount > 0) OR (type IN ('ride_payment', 'commission', 'transfer_out', 'withdrawal', 'subscription_payment') AND amount < 0) OR (type IN ('adjustment') AND amount <> 0)", name=op.f('ck_wallet_transactions_wallet_amount_sign_by_type')),
    sa.CheckConstraint('balance_after >= 0', name=op.f('ck_wallet_transactions_wallet_balance_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_wallet_transactions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_wallet_transactions_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_wallet_transactions_ride_id_rides'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_transactions')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name=op.f('uq_wallet_transactions_owner_id_idempotency_key'))
    )
    op.create_index('ix_wallet_transactions_owner_created', 'wallet_transactions', ['owner_type', 'owner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_owner_id'), 'wallet_transactions', ['owner_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_ride_id'), 'wallet_transactions', ['ride_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_type'), 'wallet_transactions', ['type'], unique=False)
    op.create_table('wallet_topup_requests',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('cliq', 'cash', 'card', name='topup_method'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'rejected', name='topup_request_status'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_wallet_topup_requests_topup_amount_positive')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_wallet_topup_requests_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_wallet_topup_requests_processed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['wallet_transactions.id'], name=op.f('fk_wallet_topup_requests_transaction_id_wallet_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_topup_requests'))
    )
    op.create_index(op.f('ix_wallet_topup_requests_owner_id'), 'wallet_topup_requests', ['owner_id'], unique=False)
    op.create_index(op.f('ix_wallet_topup_requests_status'), 'wallet_topup_requests', ['status'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('method', sa.Enum('cliq', 'bank', name='withdrawal_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', 'rejected', name='withdrawal_status'), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_withdrawal_requests_withdrawal_amount_positive')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_withdrawal_requests_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], name=op.f('fk_withdrawal_requests_processed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['wallet_transactions.id'], name=op.f('fk_withdrawal_requests_transaction_id_wallet_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_withdrawal_requests'))
    )
    op.create_index(op.f('ix_withdrawal_requests_driver_id'), 'withdrawal_requests', ['driver_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_status'), 'withdrawal_requests', ['status'], unique=False)
    # الافتراض مؤقت لملء الصفوف القائمة ثم يُنزع: قيمة العمود بعدها من الكود
    # وحده، تماماً كبقية أعمدة `users`
    op.add_column(
        'users',
        sa.Column('wallet_frozen', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('users', 'wallet_frozen', server_default=None)
    # ### end Alembic commands ###

    # «سجل قيود غير قابل للتعديل» (SPEC القسم 4) مفروضاً في القاعدة لا في
    # الكود وحده: التصحيح قيدٌ مضاد، لا تعديلُ صفٍّ ولا محوُه. TRUNCATE لا
    # يمر بمشغّلات الصفوف، فتنظيف الاختبارات يبقى عاملاً.
    op.execute(
        """
        CREATE FUNCTION wallet_transactions_append_only() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'wallet_transactions is append-only (%)', TG_OP;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER wallet_transactions_append_only
        BEFORE UPDATE OR DELETE ON wallet_transactions
        FOR EACH ROW EXECUTE FUNCTION wallet_transactions_append_only()
        """
    )


def downgrade() -> None:
    op.execute('DROP TRIGGER IF EXISTS wallet_transactions_append_only ON wallet_transactions')
    op.execute('DROP FUNCTION IF EXISTS wallet_transactions_append_only()')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_frozen')
    op.drop_index(op.f('ix_withdrawal_requests_status'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_driver_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index(op.f('ix_wallet_topup_requests_status'), table_name='wallet_topup_requests')
    op.drop_index(op.f('ix_wallet_topup_requests_owner_id'), table_name='wallet_topup_requests')
    op.drop_table('wallet_topup_requests')
    op.drop_index(op.f('ix_wallet_transactions_type'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_ride_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_owner_id'), table_name='wallet_transactions')
    op.drop_index('ix_wallet_transactions_owner_created', table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_wallet_settings_country_code'), table_name='wallet_settings')
    op.drop_table('wallet_settings')
    # ### end Alembic commands ###

    # postgres لا يُسقط ENUM مع جدوله — بدون هذا يفشل upgrade بعد downgrade
    op.execute('DROP TYPE IF EXISTS withdrawal_status')
    op.execute('DROP TYPE IF EXISTS withdrawal_method')
    op.execute('DROP TYPE IF EXISTS topup_request_status')
    op.execute('DROP TYPE IF EXISTS topup_method')
    op.execute('DROP TYPE IF EXISTS wallet_transaction_type')
    op.execute('DROP TYPE IF EXISTS wallet_owner_type')
