"""payments route points ratings saved cards

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-10 01:40:56.275659
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `currency` أنشأته ترحيلة سابقة، و`payment_provider` يُنشأ مع أول جدول
    # يستعمله (saved_cards) فيأتي في `payments` بـ `create_type=False`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_cards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('telr', name='payment_provider'), nullable=False),
    sa.Column('provider_token', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=32), nullable=True),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('expiry_month', sa.SmallInteger(), nullable=False),
    sa.Column('expiry_year', sa.SmallInteger(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(last4) = 4', name=op.f('ck_saved_cards_saved_card_last4_length')),
    sa.CheckConstraint('expiry_month BETWEEN 1 AND 12', name=op.f('ck_saved_cards_saved_card_expiry_month_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_cards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_cards')),
    sa.UniqueConstraint('user_id', 'provider', 'provider_token', name=op.f('uq_saved_cards_user_id_provider_provider_token'))
    )
    op.create_index(op.f('ix_saved_cards_user_id'), 'saved_cards', ['user_id'], unique=False)
    op.create_table('ratings',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('rater_type', sa.Enum('rider', 'driver', name='rating_rater_type'), nullable=False),
    sa.Column('rater_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name=op.f('ck_ratings_rating_stars_range')),
    sa.ForeignKeyConstraint(['rater_id'], ['users.id'], name=op.f('fk_ratings_rater_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_ratings_ride_id_rides'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ratings')),
    sa.UniqueConstraint('ride_id', 'rater_type', name=op.f('uq_ratings_ride_id_rater_type'))
    )
    op.create_index(op.f('ix_ratings_rater_id'), 'ratings', ['rater_id'], unique=False)
    op.create_index(op.f('ix_ratings_ride_id'), 'ratings', ['ride_id'], unique=False)
    op.create_table('ride_route_points',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_ride_route_points_ride_id_rides'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ride_route_points'))
    )
    op.create_index('ix_ride_route_points_ride_created', 'ride_route_points', ['ride_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ride_route_points_ride_id'), 'ride_route_points', ['ride_id'], unique=False)
    op.create_table('payments',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.Enum('cash', 'cliq', 'card', 'wallet', name='payment_method'), nullable=False),
    sa.Column('provider', postgresql.ENUM('telr', name='payment_provider', create_type=False), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', postgresql.ENUM('LYD', 'JOD', name='currency', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', 'disputed', 'refunded', name='payment_status'), nullable=False),
    sa.Column('confirmed_by', sa.Enum('driver', 'system', 'admin', name='payment_confirmed_by'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('dispute_reason', sa.String(length=255), nullable=True),
    sa.Column('disputed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Enum('paid', 'unpaid', name='dispute_resolution'), nullable=True),
    sa.Column('resolution_note', sa.String(length=255), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(resolution IS NULL) = (resolved_at IS NULL)', name=op.f('ck_payments_payment_resolution_complete')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_payment_amount_positive')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_payments_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_payments_ride_id_rides'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['wallet_transactions.id'], name=op.f('fk_payments_transaction_id_wallet_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('idempotency_key', name='uq_payments_idempotency_key')
    )
    op.create_index(op.f('ix_payments_ride_id'), 'payments', ['ride_id'], unique=False)
    op.create_index('ix_payments_ride_status', 'payments', ['ride_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.add_column('rides', sa.Column('actual_distance_km', sa.Numeric(precision=8, scale=3), nullable=True))
    op.create_check_constraint(op.f('ck_rides_ride_actual_distance_non_negative'), 'rides', 'actual_distance_km IS NULL OR actual_distance_km >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_rides_ride_actual_distance_non_negative'), 'rides', type_='check')
    op.drop_column('rides', 'actual_distance_km')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index('ix_payments_ride_status', table_name='payments')
    op.drop_index(op.f('ix_payments_ride_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_ride_route_points_ride_id'), table_name='ride_route_points')
    op.drop_index('ix_ride_route_points_ride_created', table_name='ride_route_points')
    op.drop_table('ride_route_points')
    op.drop_index(op.f('ix_ratings_ride_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_rater_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_saved_cards_user_id'), table_name='saved_cards')
    op.drop_table('saved_cards')
    # ### end Alembic commands ###

    # postgres لا يُسقط ENUM مع جدوله — بدون هذا يفشل upgrade بعد downgrade.
    # `currency` ليس منها: أنشأته ترحيلة سابقة وما زالت جداولها تستعمله.
    op.execute('DROP TYPE IF EXISTS dispute_resolution')
    op.execute('DROP TYPE IF EXISTS payment_confirmed_by')
    op.execute('DROP TYPE IF EXISTS payment_status')
    op.execute('DROP TYPE IF EXISTS payment_method')
    op.execute('DROP TYPE IF EXISTS payment_provider')
    op.execute('DROP TYPE IF EXISTS rating_rater_type')
