"""provider orders for card payments

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-10 02:34:23.817361
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0008'
down_revision: str | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # `payment_provider` و`country_code` و`currency` أنشأتها ترحيلات سابقة، فهي
    # هنا بـ `create_type=False` — وبغيره يفشل upgrade بـ "type already exists".
    # الجديدان وحدهما يُنشآن: `provider_order_purpose` و`provider_order_status`.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_orders',
    sa.Column('provider', postgresql.ENUM('telr', name='payment_provider', create_type=False), nullable=False),
    sa.Column('purpose', sa.Enum('ride_payment', 'wallet_topup', name='provider_order_purpose'), nullable=False),
    sa.Column('status', sa.Enum('created', 'paid', 'failed', 'cancelled', name='provider_order_status'), nullable=False),
    sa.Column('cart_id', sa.String(length=25), nullable=False),
    sa.Column('provider_order_ref', sa.String(length=120), nullable=True),
    sa.Column('redirect_url', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('currency', postgresql.ENUM('LYD', 'JOD', name='currency', create_type=False), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('save_card', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('refund_ref', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(purpose = 'ride_payment') = (payment_id IS NOT NULL)", name=op.f('ck_provider_orders_provider_order_payment_matches_purpose')),
    sa.CheckConstraint("(purpose = 'ride_payment') = (ride_id IS NOT NULL)", name=op.f('ck_provider_orders_provider_order_ride_matches_purpose')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_provider_orders_provider_order_amount_positive')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_provider_orders_payment_id_payments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_provider_orders_ride_id_rides'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['wallet_transactions.id'], name=op.f('fk_provider_orders_transaction_id_wallet_transactions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_provider_orders_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_orders')),
    sa.UniqueConstraint('cart_id', name='uq_provider_orders_cart_id')
    )
    op.create_index('ix_provider_orders_provider_ref', 'provider_orders', ['provider', 'provider_order_ref'], unique=False)
    op.create_index(op.f('ix_provider_orders_ride_id'), 'provider_orders', ['ride_id'], unique=False)
    op.create_index(op.f('ix_provider_orders_status'), 'provider_orders', ['status'], unique=False)
    op.create_index(op.f('ix_provider_orders_user_id'), 'provider_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_orders_user_id'), table_name='provider_orders')
    op.drop_index(op.f('ix_provider_orders_status'), table_name='provider_orders')
    op.drop_index(op.f('ix_provider_orders_ride_id'), table_name='provider_orders')
    op.drop_index('ix_provider_orders_provider_ref', table_name='provider_orders')
    op.drop_table('provider_orders')
    # ### end Alembic commands ###

    # postgres لا يُسقط ENUM مع جدوله — بدون هذا يفشل upgrade بعد downgrade.
    # الثلاثة الأخرى ليست هنا: أنشأتها ترحيلات سابقة وما زالت جداولها تستعملها.
    op.execute('DROP TYPE IF EXISTS provider_order_status')
    op.execute('DROP TYPE IF EXISTS provider_order_purpose')
