"""driver subscriptions

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-10 03:12:25.161598
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0009'
down_revision: str | None = '0008'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # قيمة جديدة على نوعٍ قائم — لا نوع جديد. `IF NOT EXISTS` يجعلها قابلة
    # للإعادة بعد downgrade جزئي إلى `0008` (الذي لا يُسقط النوع لأن جدوله باقٍ).
    #
    # postgres يسمح بإضافة القيمة داخل معاملة لكنه يمنع **استعمالها** فيها،
    # ولذلك قيدُ `provider_orders` أدناه يقارن `purpose::text` لا قيمة الـ ENUM:
    # بغير ذلك ما كان العمودُ وقيدُه ليولدا في ترحيلة واحدة.
    op.execute("ALTER TYPE provider_order_purpose ADD VALUE IF NOT EXISTS 'subscription'")

    # `payment_method` أنشأته ترحيلة `0007` وما زال جدولها يستعمله، فهو هنا
    # بـ `create_type=False` — وبغيره يفشل upgrade بـ "type already exists".
    # `subscription_status` وحده جديد.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_subscriptions',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('payment_method', postgresql.ENUM('cash', 'cliq', 'card', 'wallet', name='payment_method', create_type=False), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', name='subscription_status'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_paid >= 0', name=op.f('ck_driver_subscriptions_subscription_amount_non_negative')),
    sa.CheckConstraint('expires_at > starts_at', name=op.f('ck_driver_subscriptions_subscription_period_positive')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_driver_subscriptions_driver_id_drivers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_driver_subscriptions_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['wallet_transactions.id'], name=op.f('fk_driver_subscriptions_transaction_id_wallet_transactions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_subscriptions')),
    sa.UniqueConstraint('idempotency_key', name='uq_driver_subscriptions_idempotency_key')
    )
    op.create_index('ix_driver_subscriptions_driver_expires', 'driver_subscriptions', ['driver_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_driver_subscriptions_driver_id'), 'driver_subscriptions', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_subscriptions_plan_id'), 'driver_subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_driver_subscriptions_status'), 'driver_subscriptions', ['status'], unique=False)
    op.add_column('provider_orders', sa.Column('plan_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_provider_orders_plan_id_subscription_plans'), 'provider_orders', 'subscription_plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_provider_orders_provider_order_plan_matches_purpose'), 'provider_orders', "(purpose::text = 'subscription') = (plan_id IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_provider_orders_provider_order_plan_matches_purpose'), 'provider_orders', type_='check')
    op.drop_constraint(op.f('fk_provider_orders_plan_id_subscription_plans'), 'provider_orders', type_='foreignkey')
    op.drop_column('provider_orders', 'plan_id')
    op.drop_index(op.f('ix_driver_subscriptions_status'), table_name='driver_subscriptions')
    op.drop_index(op.f('ix_driver_subscriptions_plan_id'), table_name='driver_subscriptions')
    op.drop_index(op.f('ix_driver_subscriptions_driver_id'), table_name='driver_subscriptions')
    op.drop_index('ix_driver_subscriptions_driver_expires', table_name='driver_subscriptions')
    op.drop_table('driver_subscriptions')
    # ### end Alembic commands ###

    # postgres لا يُسقط ENUM مع جدوله — بدون هذا يفشل upgrade بعد downgrade.
    op.execute('DROP TYPE IF EXISTS subscription_status')
    # قيمة `subscription` في `provider_order_purpose` لا تُحذف: postgres لا
    # يعرف حذف قيمة من ENUM، والنوع كله تُسقطه ترحيلة `0008` في تراجعها. فمن
    # تراجع إلى `0008` وحدها يجد القيمة باقيةً بلا ضرر — لا عمود يستعملها.
