"""سياسات الدفع لكل دولة، ومهلة تأكيد حوالة كليك مجمَّدةً على الدفعة

SPEC القسم 6.2/6: «عند الرفض أو انقضاء مهلة التأكيد → `disputed`».

`payment_settings` تحمل الرقم لكل دولة (يديره المشرف)، و
`payments.cliq_confirmation_expires_at` تحمل **الموعد المجمَّد** لحظة إدخال
المرجع — فتعديلُ الإعداد لا يحرّك مهلةَ دفعةٍ قائمة، كما لا تُعاد قراءة
`commission_percent_at_ride`. ولا نوعَ ENUM جديداً هنا، فلا `DROP TYPE` في
التراجع.

payment settings and cliq confirmation deadline

Revision ID: 0015
Revises: 0014
Create Date: 2026-08-11 03:09:29.698328
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0015'
down_revision: str | None = '0014'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_settings',
    # النوع أنشأته ترحيلةٌ سابقة — `create_type=False` وإلا فشل الترقية بـ
    # «type already exists» (نفس ما تفعله 0003)
    sa.Column(
        'country_code',
        postgresql.ENUM('LY', 'JO', name='country_code', create_type=False),
        nullable=False,
    ),
    sa.Column('cliq_confirmation_hours', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cliq_confirmation_hours > 0', name=op.f('ck_payment_settings_payment_cliq_confirmation_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_settings'))
    )
    op.create_index(op.f('ix_payment_settings_country_code'), 'payment_settings', ['country_code'], unique=True)
    op.add_column('payments', sa.Column('cliq_confirmation_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_payments_cliq_confirmation_expires_at'), 'payments', ['cliq_confirmation_expires_at'], unique=False)
    op.create_check_constraint(op.f('ck_payments_payment_cliq_deadline_needs_reference'), 'payments', 'cliq_confirmation_expires_at IS NULL OR cliq_reference_at IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_payments_payment_cliq_deadline_needs_reference'), 'payments', type_='check')
    op.drop_index(op.f('ix_payments_cliq_confirmation_expires_at'), table_name='payments')
    op.drop_column('payments', 'cliq_confirmation_expires_at')
    op.drop_index(op.f('ix_payment_settings_country_code'), table_name='payment_settings')
    op.drop_table('payment_settings')
    # ### end Alembic commands ###
