"""المهامُّ والمستوياتُ والشارات (البند ٥٣، `design/MISSIONS-LEVELS.md`)

**وثلاثةُ جداولَ لا واحد**، وفصلُها هو التصميم: المهمّةَ تكتبها الإدارة،
والمستوى مهمّةٌ دوريةٌ وحدَها (عمودان على `drivers`)، والشارةَ المشرفُ بيده.

**والحدُّ الأقصى للأثر في القاعدة أيضاً**: ١٠٠م بقرار المالك — حارسٌ لا يعتمد
على طبقةٍ عليا، فرقمٌ يمرّ منها لا يجوز أن يجد الجدولَ مفتوحاً بعده.

Revision ID: 0040
Revises: 0039
Create Date: 2026-08-16 17:44:48.894570
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0040'
down_revision: str | None = '0039'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=48), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_badges')),
    sa.UniqueConstraint('key', name='uq_badges_key')
    )
    op.create_table('level_settings',
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('discount_meters', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_meters >= 0 AND discount_meters <= 100', name=op.f('ck_level_settings_level_discount_within_cap')),
    sa.CheckConstraint('level >= 0 AND level <= 3', name=op.f('ck_level_settings_level_setting_in_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level_settings')),
    sa.UniqueConstraint('country_code', 'level', name='uq_level_settings_country')
    )
    op.create_index(op.f('ix_level_settings_country_code'), 'level_settings', ['country_code'], unique=False)
    op.create_table('missions',
    sa.Column('country_code', postgresql.ENUM('LY', 'JO', name='country_code', create_type=False), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('target', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('EXTRACT(DAY FROM month) = 1', name=op.f('ck_missions_mission_month_is_first')),
    sa.CheckConstraint('target > 0', name=op.f('ck_missions_mission_target_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_missions_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_missions')),
    sa.UniqueConstraint('country_code', 'month', 'metric', name='uq_missions_country_month_metric')
    )
    op.create_index(op.f('ix_missions_country_code'), 'missions', ['country_code'], unique=False)
    op.create_index(op.f('ix_missions_month'), 'missions', ['month'], unique=False)
    op.create_table('driver_badges',
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], name=op.f('fk_driver_badges_badge_id_badges'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_driver_badges_driver_id_drivers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_driver_badges_granted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_badges')),
    sa.UniqueConstraint('driver_id', 'badge_id', name='uq_driver_badges')
    )
    op.create_index(op.f('ix_driver_badges_driver_id'), 'driver_badges', ['driver_id'], unique=False)
    op.add_column('drivers', sa.Column('level', sa.SmallInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('drivers', sa.Column('level_computed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'level_computed_at')
    op.drop_column('drivers', 'level')
    op.drop_index(op.f('ix_driver_badges_driver_id'), table_name='driver_badges')
    op.drop_table('driver_badges')
    op.drop_index(op.f('ix_missions_month'), table_name='missions')
    op.drop_index(op.f('ix_missions_country_code'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_level_settings_country_code'), table_name='level_settings')
    op.drop_table('level_settings')
    op.drop_table('badges')
    # ### end Alembic commands ###
