"""جدولا النسخ الاحتياطي: الإعداداتُ والسجلّ (`design/BACKUP-AND-RESTORE.md`)

**والإعداداتُ صفٌّ واحدٌ عامٌّ لا per-country**: الخادمُ واحدٌ وقاعدةُ البيانات
واحدة — كـ`security_settings` بالضبط.

Revision ID: 0041
Revises: 0040
Create Date: 2026-08-16 19:18:02.583427
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0041'
down_revision: str | None = '0040'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_runs',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('alembic_revision', sa.String(length=32), nullable=True),
    sa.Column('encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_runs'))
    )
    op.create_index(op.f('ix_backup_runs_name'), 'backup_runs', ['name'], unique=False)
    op.create_table('backup_settings',
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('frequency', sa.String(length=16), server_default='daily', nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('hour_local', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('keep_count', sa.Integer(), server_default=sa.text('7'), nullable=False),
    sa.Column('alert_after_hours', sa.Integer(), server_default=sa.text('26'), nullable=False),
    sa.Column('alert_unpulled_count', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('max_bytes', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hour_local >= 0 AND hour_local <= 23', name=op.f('ck_backup_settings_backup_hour_in_day')),
    sa.CheckConstraint('keep_count > 0', name=op.f('ck_backup_settings_backup_keep_positive')),
    sa.CheckConstraint('max_bytes IS NULL OR max_bytes > 0', name=op.f('ck_backup_settings_backup_max_bytes_positive')),
    sa.CheckConstraint('weekday IS NULL OR (weekday >= 0 AND weekday <= 6)', name=op.f('ck_backup_settings_backup_weekday_in_week')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backup_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_settings')
    op.drop_index(op.f('ix_backup_runs_name'), table_name='backup_runs')
    op.drop_table('backup_runs')
    # ### end Alembic commands ###
