"""عدّادُ إعادة توجيه المسار على الرحلة (البند ١٧-٤)

**وعمودٌ لا عدّادٌ في الذاكرة**: السقفُ يجب أن يبقى بعد إعادة تشغيل العامل وبين
حاويتين، وعدّادٌ في عملية يُصفَّر بأوّل نشر — فيصير السقفُ اقتراحاً على شيءٍ
**يُنفق مالاً** (هو الشيءُ الوحيد الذي يعاود نداءَ Directions).

Revision ID: 0042
Revises: 0041
Create Date: 2026-08-16 20:16:51.782296
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0042'
down_revision: str | None = '0041'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rides', sa.Column('reroute_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'reroute_count')
    # ### end Alembic commands ###
