"""الوقفةُ غير المخطَّطة وانتظارُ الوصول (SPEC §5.10-ب)

**جدولٌ مستقلٌّ لا عمودٌ على `ride_stops`**: صفوفُ المحطات تدخل `stops_count`
وسقفَ المحطات وبطاقةَ العرض والتسعير، ووقفةٌ تُدسّ بينها تُغيّر أربعةَ أشياء لم
يطلبها أحد.

**والفهرسُ الجزئيُّ `uq_ride_pauses_open` هو حارسُ المال**: ضغطتان متزامنتان
كانتا تفتحان وقفتين فيُحتسب الوقتُ مرتين على وقفةٍ واحدة.

Revision ID: 0043
Revises: 0042
Create Date: 2026-08-16 21:27:37.951038
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0043'
down_revision: str | None = '0042'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ride_pauses',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price_per_min_at_pause', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('free_minutes_at_pause', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('max_minutes_at_pause', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_ride_pauses_ride_pause_ends_after_it_starts')),
    sa.CheckConstraint('price_per_min_at_pause >= 0 AND free_minutes_at_pause >= 0 AND max_minutes_at_pause >= 0', name=op.f('ck_ride_pauses_ride_pause_amounts_non_negative')),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_ride_pauses_ride_id_rides'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ride_pauses'))
    )
    op.create_index(op.f('ix_ride_pauses_ride_id'), 'ride_pauses', ['ride_id'], unique=False)
    op.create_index('uq_ride_pauses_open', 'ride_pauses', ['ride_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    op.add_column('pricing_rules', sa.Column('pause_price_per_min', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    op.add_column('pricing_rules', sa.Column('arrival_free_minutes', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('pricing_rules', sa.Column('pause_max_minutes', sa.SmallInteger(), server_default='0', nullable=False))
    op.create_check_constraint(op.f('ck_pricing_rules_pricing_pause_amounts_non_negative'), 'pricing_rules', 'pause_price_per_min >= 0 AND arrival_free_minutes >= 0 AND pause_max_minutes >= 0')
    op.add_column('rides', sa.Column('pause_price_per_min_at_ride', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    op.add_column('rides', sa.Column('arrival_free_minutes_at_ride', sa.SmallInteger(), server_default='0', nullable=False))
    op.add_column('rides', sa.Column('pause_max_minutes_at_ride', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rides', 'pause_max_minutes_at_ride')
    op.drop_column('rides', 'arrival_free_minutes_at_ride')
    op.drop_column('rides', 'pause_price_per_min_at_ride')
    op.drop_constraint(op.f('ck_pricing_rules_pricing_pause_amounts_non_negative'), 'pricing_rules', type_='check')
    op.drop_column('pricing_rules', 'pause_max_minutes')
    op.drop_column('pricing_rules', 'arrival_free_minutes')
    op.drop_column('pricing_rules', 'pause_price_per_min')
    op.drop_index('uq_ride_pauses_open', table_name='ride_pauses', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index(op.f('ix_ride_pauses_ride_id'), table_name='ride_pauses')
    op.drop_table('ride_pauses')
    # ### end Alembic commands ###
