"""subscription offers

Revision ID: 0044
Revises: 0043
Create Date: 2026-08-18 23:30:14.502923
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0044'
down_revision: str | None = '0043'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_offers',
    # **`create_type=False`**: `country_code` أنشأته ترحيلةٌ سابقة، والتوليدُ
    # التلقائيُّ يعيد إصداره فتفشل الترقيةُ بـ«type already exists» — نفسُ ما
    # عالجته `0003`.
    sa.Column(
        'country_code',
        postgresql.ENUM('LY', 'JO', name='country_code', create_type=False),
        nullable=False,
    ),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('discount_type', sa.String(length=16), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_discount', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('audience', sa.String(length=24), nullable=False),
    sa.Column('lapsed_days', sa.SmallInteger(), nullable=True),
    sa.Column('max_uses_per_driver', sa.SmallInteger(), nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discount_value > 0 AND discount_value <= 100', name=op.f('ck_subscription_offers_subscription_offer_percent_range')),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at', name=op.f('ck_subscription_offers_subscription_offer_window_positive')),
    sa.CheckConstraint('lapsed_days IS NULL OR lapsed_days > 0', name=op.f('ck_subscription_offers_subscription_offer_lapsed_days_positive')),
    sa.CheckConstraint('max_uses_per_driver >= 0', name=op.f('ck_subscription_offers_subscription_offer_uses_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_subscription_offers_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('fk_subscription_offers_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_offers')),
    sa.UniqueConstraint('country_code', 'name', name='uq_subscription_offers_name')
    )
    op.create_index('ix_subscription_offers_country_active', 'subscription_offers', ['country_code', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscription_offers_country_code'), 'subscription_offers', ['country_code'], unique=False)
    op.create_index(op.f('ix_subscription_offers_plan_id'), 'subscription_offers', ['plan_id'], unique=False)
    op.create_table('subscription_offer_grants',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_subscription_offer_grants_driver_id_drivers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_subscription_offer_grants_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['subscription_offers.id'], name=op.f('fk_subscription_offer_grants_offer_id_subscription_offers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_offer_grants')),
    sa.UniqueConstraint('offer_id', 'driver_id', name='uq_subscription_offer_grant_driver')
    )
    op.create_index(op.f('ix_subscription_offer_grants_driver_id'), 'subscription_offer_grants', ['driver_id'], unique=False)
    op.create_index(op.f('ix_subscription_offer_grants_offer_id'), 'subscription_offer_grants', ['offer_id'], unique=False)
    op.add_column('driver_subscriptions', sa.Column('offer_id', sa.UUID(), nullable=True))
    op.add_column('driver_subscriptions', sa.Column('discount_amount', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    op.add_column('driver_subscriptions', sa.Column('offer_discount_amount', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    op.add_column('driver_subscriptions', sa.Column('list_price', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False))
    op.create_index(op.f('ix_driver_subscriptions_offer_id'), 'driver_subscriptions', ['offer_id'], unique=False)
    op.create_foreign_key(op.f('fk_driver_subscriptions_offer_id_subscription_offers'), 'driver_subscriptions', 'subscription_offers', ['offer_id'], ['id'], ondelete='RESTRICT')
    op.create_check_constraint(op.f('ck_driver_subscriptions_offer_discount_non_negative'), 'driver_subscriptions', 'offer_discount_amount >= 0')
    op.create_check_constraint(op.f('ck_driver_subscriptions_subscription_discount_non_negative'), 'driver_subscriptions', 'discount_amount >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_driver_subscriptions_subscription_discount_non_negative'), 'driver_subscriptions', type_='check')
    op.drop_constraint(op.f('ck_driver_subscriptions_offer_discount_non_negative'), 'driver_subscriptions', type_='check')
    op.drop_constraint(op.f('fk_driver_subscriptions_offer_id_subscription_offers'), 'driver_subscriptions', type_='foreignkey')
    op.drop_index(op.f('ix_driver_subscriptions_offer_id'), table_name='driver_subscriptions')
    op.drop_column('driver_subscriptions', 'list_price')
    op.drop_column('driver_subscriptions', 'offer_discount_amount')
    op.drop_column('driver_subscriptions', 'discount_amount')
    op.drop_column('driver_subscriptions', 'offer_id')
    op.drop_index(op.f('ix_subscription_offer_grants_offer_id'), table_name='subscription_offer_grants')
    op.drop_index(op.f('ix_subscription_offer_grants_driver_id'), table_name='subscription_offer_grants')
    op.drop_table('subscription_offer_grants')
    op.drop_index(op.f('ix_subscription_offers_plan_id'), table_name='subscription_offers')
    op.drop_index(op.f('ix_subscription_offers_country_code'), table_name='subscription_offers')
    op.drop_index('ix_subscription_offers_country_active', table_name='subscription_offers')
    op.drop_table('subscription_offers')
    # ### end Alembic commands ###
