"""rider photo and its report

Revision ID: 0053
Revises: 0052
Create Date: 2026-08-22 01:52:21.583959
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0053'
down_revision: str | None = '0052'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_photo_reports',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_user_photo_reports_reported_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_user_photo_reports_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], name=op.f('fk_user_photo_reports_ride_id_rides'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['users.id'], name=op.f('fk_user_photo_reports_subject_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_photo_reports')),
    sa.UniqueConstraint('subject_id', 'reported_by', 'resolved_at', name='uq_photo_report_open')
    )
    op.create_index(op.f('ix_user_photo_reports_reported_by'), 'user_photo_reports', ['reported_by'], unique=False)
    op.create_index(op.f('ix_user_photo_reports_ride_id'), 'user_photo_reports', ['ride_id'], unique=False)
    op.create_index(op.f('ix_user_photo_reports_subject_id'), 'user_photo_reports', ['subject_id'], unique=False)
    # **ولا يركب معها ما ليس منها**: أسقط التوليدُ الآليُّ تعديلاً على
    # `otp_message_templates.id` (فرقُ `server_default` بين النموذج والقاعدة)
    # — **وهو ليس من هذا التغيير**. وترحيلةٌ تحمل ما لم يُقصد تجعل الرجوعَ
    # عنها يُرجع ما لم يُرفع.
    op.add_column('users', sa.Column('photo_path', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('photo_hidden_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo_hidden_at')
    op.drop_column('users', 'photo_path')
    op.drop_index(op.f('ix_user_photo_reports_subject_id'), table_name='user_photo_reports')
    op.drop_index(op.f('ix_user_photo_reports_ride_id'), table_name='user_photo_reports')
    op.drop_index(op.f('ix_user_photo_reports_reported_by'), table_name='user_photo_reports')
    op.drop_table('user_photo_reports')
    # ### end Alembic commands ###
