"""map settings per country

Revision ID: 0054
Revises: 0053
Create Date: 2026-08-22 02:30:07.716699
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0054'
down_revision: str | None = '0053'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_settings',
        # **النوعُ موجودٌ من ترحيلةٍ سابقة** — و`create_type=False` هي ما يمنع
    # `CREATE TYPE` ثانيةً فيفشل `upgrade` بـ«type already exists»
    sa.Column(
        'country_code',
        postgresql.ENUM('LY', 'JO', name='country_code', create_type=False),
        nullable=False,
    ),
    sa.Column('nearby_radius_km', sa.Numeric(precision=5, scale=2), server_default=sa.text('3.0'), nullable=False),
    sa.Column('nearby_max_count', sa.Integer(), server_default=sa.text('50'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('nearby_radius_km > 0 AND nearby_max_count > 0', name=op.f('ck_map_settings_positive')),
    sa.PrimaryKeyConstraint('country_code', name=op.f('pk_map_settings'))
    )
    # **ولا يركب معها ما ليس منها**: أسقط التوليدُ الآليُّ تعديلاً على
    # `otp_message_templates.id` — فرقٌ في `server_default` بين النموذج
    # والقاعدة **ليس من هذا التغيير**، وترحيلةٌ تحمل ما لم يُقصد تجعل الرجوعَ
    # عنها يُرجع ما لم يُرفع.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_settings')
    # ### end Alembic commands ###
