"""vehicle skins catalogue and ownership

Revision ID: 0055
Revises: 0054
Create Date: 2026-08-22 03:06:21.277786
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '0055'
down_revision: str | None = '0054'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_skins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('asset_key', sa.String(length=64), nullable=True),
    sa.Column('store_image_path', sa.String(length=512), nullable=True),
    sa.Column('map_image_path', sa.String(length=512), nullable=True),
    sa.Column('map_scale_percent', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('map_rotates', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('visible_before_accept', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('max_supply', sa.Integer(), nullable=True),
    sa.Column('level_required', sa.Integer(), nullable=True),
    sa.Column('is_gift', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_public_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_feminine', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('feminine_drivers_only', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rarity IN ('common','premium','rare','legendary')", name=op.f('ck_vehicle_skins_vehicle_skins_rarity')),
    sa.CheckConstraint('level_required IS NULL OR level_required > 0', name=op.f('ck_vehicle_skins_vehicle_skins_level')),
    sa.CheckConstraint('max_supply IS NULL OR max_supply > 0', name=op.f('ck_vehicle_skins_vehicle_skins_supply')),
    sa.CheckConstraint('valid_from IS NULL OR valid_until IS NULL OR valid_until > valid_from', name=op.f('ck_vehicle_skins_vehicle_skins_season')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicle_skins'))
    )
    op.create_index('ix_vehicle_skins_active', 'vehicle_skins', ['is_active'], unique=False)
    op.create_table('vehicle_skin_prices',
    sa.Column('skin_id', sa.UUID(), nullable=False),
    # **النوعُ موجودٌ من ترحيلةٍ سابقة** — و`create_type=False` تمنع
    # `CREATE TYPE` ثانيةً فيفشل `upgrade` بـ«type already exists»
    sa.Column(
        'country_code',
        postgresql.ENUM('LY', 'JO', name='country_code', create_type=False),
        nullable=False,
    ),
    sa.Column('price', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name=op.f('ck_vehicle_skin_prices_vehicle_skin_prices_positive')),
    sa.ForeignKeyConstraint(['skin_id'], ['vehicle_skins.id'], name=op.f('fk_vehicle_skin_prices_skin_id_vehicle_skins'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skin_id', 'country_code', name=op.f('pk_vehicle_skin_prices'))
    )
    op.create_table('driver_vehicle_skins',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('skin_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('gift','purchase','grant')", name=op.f('ck_driver_vehicle_skins_driver_skins_source')),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], name=op.f('fk_driver_vehicle_skins_driver_id_drivers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skin_id'], ['vehicle_skins.id'], name=op.f('fk_driver_vehicle_skins_skin_id_vehicle_skins'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_vehicle_skins')),
    sa.UniqueConstraint('driver_id', 'skin_id', name='uq_driver_skin')
    )
    op.create_index(op.f('ix_driver_vehicle_skins_driver_id'), 'driver_vehicle_skins', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_vehicle_skins_skin_id'), 'driver_vehicle_skins', ['skin_id'], unique=False)
    op.add_column('drivers', sa.Column('active_skin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_drivers_active_skin_id_vehicle_skins'), 'drivers', 'vehicle_skins', ['active_skin_id'], ['id'], ondelete='SET NULL')
    # **ولا يركب معها ما ليس منها**: تعديلُ `otp_message_templates.id` فرقٌ
    # قائمٌ بين النموذج والقاعدة **ليس من هذا التغيير**، وترحيلةٌ تحمل ما لم
    # يُقصد تجعل الرجوعَ عنها يُرجع ما لم يُرفع.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # **ولا يركب معها ما ليس منها**: تعديلُ `otp_message_templates.id` فرقٌ
    # قائمٌ بين النموذج والقاعدة **ليس من هذا التغيير**، وترحيلةٌ تحمل ما لم
    # يُقصد تجعل الرجوعَ عنها يُرجع ما لم يُرفع.
    op.drop_constraint(op.f('fk_drivers_active_skin_id_vehicle_skins'), 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'active_skin_id')
    op.drop_index(op.f('ix_driver_vehicle_skins_skin_id'), table_name='driver_vehicle_skins')
    op.drop_index(op.f('ix_driver_vehicle_skins_driver_id'), table_name='driver_vehicle_skins')
    op.drop_table('driver_vehicle_skins')
    op.drop_table('vehicle_skin_prices')
    op.drop_index('ix_vehicle_skins_active', table_name='vehicle_skins')
    op.drop_table('vehicle_skins')
    # ### end Alembic commands ###
